sudo: required
language: python
services:
  - docker
python:
  - "3.5"
before_script:
- docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
- docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 bash
- mysql -uroot -p'$3cureUS' -h db
- create user 'www'@'%' identified by '$3cureUS';
- create database cs4501 character set utf8;
- grant all on cs4501.* to 'www'@'%';
- grant all on test_cs4501.* to 'www'@'%';
- quit
- exit
script:
- docker-compose up -d
- docker exec cs4501site_models_1 bash -c "python manage.py test"