models:
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - ./isa_site:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata isa_models/fixtures/fixture1.json && mod_wsgi-express start-server --log-to-terminal --working-directory /app --reload-on-changes /app/isa_site/wsgi.py"

exp:
    image: tp33/django
    links:
      - models:models-api
      - kafka:kafka
      - es:es
    volumes:
      - ./isa_exp:/app
    ports:
      - "8002:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory /app --log-to-terminal --reload-on-changes /app/isa_exp/wsgi.py"

web:
   image: abr8xq/phantomjs
   links:
      - exp:exp-api
   ports:
      - "8003:8000"
   volumes:
      - ./isa_web:/app
   command: "mod_wsgi-express start-server --log-to-terminal --reload-on-changes /app/isa_web/wsgi.py"

web2:
   image: abr8xq/phantomjs
   links:
      - exp:exp-api
   ports:
      - "8004:8000"
   volumes:
      - ./isa_web:/app
   command: "mod_wsgi-express start-server --log-to-terminal --reload-on-changes /app/isa_web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - .:/app
   command: bash -c "python search_indexer.py"

haproxy:
    image: abr8xq/haproxy
    container_name: haproxy
    ports:
      - "8005:80"
    links:
      - web:web1
      - web2:web2

