models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ~/cs4501/app/cs4501-site/isa_site:/app
    ports:
      - "8001:8000"
    command: bash -c "python /app/isa_site/manage.py runserver 0.0.0.0:8000"